from typing import Any, Dict, List, Optional, Protocol


class Collector(Protocol):
    def collect(self) -> List[Dict[str, Any]]: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...


class FeatureExtractor(Protocol):
    def extract_all_features(self, telemetry: Dict[str, Any]) -> Any: ...

    def get_feature_names(self) -> List[str]: ...


class Detector(Protocol):
    def detect(self, features: Any) -> Any: ...

    def get_health(self) -> Dict[str, Any]: ...

    def save_model(self, file_path: Optional[str] = None) -> bool: ...

    def load_model(self, file_path: Optional[str] = None) -> bool: ...

    @property
    def is_trained(self) -> bool: ...


class AlertEngine(Protocol):
    def process_anomaly(self, anomaly: Dict, explanation: Dict) -> Optional[Dict]: ...


class SyncQueue(Protocol):
    async def enqueue(
        self, item_type: str, item_data: Dict[str, Any], priority: int = 0
    ) -> bool: ...

    async def initialize(self) -> None: ...

    async def start_worker(self, sync_client: Any) -> None: ...

    async def stop(self) -> None: ...

    def get_stats(self) -> Dict[str, Any]: ...
